### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by andybotting** [romanvm/Kodistubs#13]
I'm starting to get my add-ons into shape to support Python 2 and 3. There's a few bits I've found to make this work with Py3

What I've found so far is:
  * str is now unicode, so unicode can't be found
  * long is now int, so no longs, so 0L is invalid in Python 3
  * sys.maxint is now sys.maxsize in Python 3

I can send up a pull request with some handling of these between Python 2 and 3 if you're interested. I haven't actually built Kodi yet with Python 3 support so see if there's any major differences Kodi makes when using Python 3 though.

**Comment by romanvm** [comment]
The current Kodi version still includes with Python 2 so I would recommend to use Python 2 in your working environment and this library https://github.com/romanvm/kodi.six for mitigating version differences. And **six** or **future** library for general version portability.

**Comment by andybotting** [comment]
Thanks, that looks really useful.

I was more looking at the testing part of it for now. Am I right in thinking that Kodistubs will still need to be updated to support testing with Python 3?

**Comment by romanvm** [comment]
Yes, but not just "updated". Currently, they are generated with a script, so the script itself need to be updated to generate correct stubs from Kodi/Python 3 version.

**Comment by vlmaksime** [comment]
@andybotting 
You can try my fork https://github.com/vlmaksime/Kodistubs
I implemented in it emulation of execution of commands.
Here is an example of my test script https://github.com/vlmaksime/plugin.video.filmix/blob/master/tests.py
But it's not upgraded to version 18.

**Comment by andybotting** [comment]
Thanks @vlmaksime. Your test script looks very interesting. Thanks for sharing.

Looks like there's no hurry, so I'll just wait for @romanvm to update his script.

**Comment by matthuisman** [comment]
+1 for Python3 stubs as Python3 now merged in kodi master.

**Comment by Gujal00** [comment]
Please release kodistubs for Python3 as the nightlies have been on Python3 for a while now. Thanks

**Comment by vlmaksime** [comment]
Kodistubs in my [develop branch](https://github.com/vlmaksime/Kodistubs/tree/develop) is adopted for Python 3

**Comment by romanvm** [comment]
I'm closing this issue because I don't see the point in porting Kodistubs v.18 to Python 3. Development for Kodi 18 can be done using Python 2.7 environment, even if you want to write Python 2/3 compatible code. Kodistubs v.19 will be released as soon as Kodi 19 "Matrix" has stable Python API and they, of course, will be in Python 3 and reflect the actual state of Python API that has some breaking changes because of cleaning deprecated stuff.

**Comment by romanvm** [comment]
I have created `matrix` branch in the repo that contains Kodistubs generated from Kodi `master` branch (future 19 "Matrix") using the updated generator script. The stub files are fully Python 3 compatible including function/method signatures with type annotations.

Note that this is a very early version that has had only minimal post-editing to fix obvious syntax errors in the code so docstrings formatting may be weird at many places. The new Kodistubs can be installed using pip: `pip install -q git+https://github.com/romanvm/Kodistubs.git@matrix`.
