### ISSUE TITLE
Can't find "legacy" branch

### ISSUE THREAD

**Issue by ZacWolf** [romanvm/Kodistubs#14]
I can't find the "legacy" branch. I looking for what version I need for doing Krypton 17.6 dev against? There are some big changes in Leia 18 that are throwing false negatives (method/property not found).

It would be really awesome if you used the GitHub "releases" function so it would be very easy to download a specific version (and/or to know which versions are available via pip).

**Comment by romanvm** [comment]
I have no idea why you cannot find older versions of Kodistubs. `legacy` branch is there: https://github.com/romanvm/Kodistubs/tree/legacy but it's really legacy. And "Releases" tab does contain version tags with links to archived repo snapshots for the respective versions. Also 17.x versions can be installed from PyPI by specifying a specific version in `pip install`. But I need to warn you that 17.x versions are missing callback methods for `xbmc.Player` and `xbmcgui.Window` classes. This was a result of a bug in stubs generator script that was fixed only in version 18.0.
