### ISSUE TITLE
xbmcvfs.exists does not handle relative file paths

### ISSUE THREAD

**Issue by Reptarsrage** [romanvm/Kodistubs#15]
Kodistubs 18.0.0
Kodi 18.3

Seeing this issue in the Internet Archive Gamer Launcher here: https://github.com/zach-morris/plugin.program.iagl/issues/101

Relative file paths such as `~/.config/retroarch/cores` are not supported for the method `xbmcvfs.exists`. It will always return false even if directory exists. Using absolute paths fixes the issue. Any workaround here? Is it possible to resolve the relative file path before calling `xbmcvfs.exists`?

**Comment by romanvm** [comment]
I don't see how your question is related to this project. Kodistubs do not contain any working code by design and cannot resolve paths, relative or not. If you have a question about Kodi functionality, please post a question on Kodi forum in the respective section: https://forum.kodi.tv

**Comment by Reptarsrage** [comment]
My bad, I don’t understand what this library does. Well maybe you can help me track down the issue. What’s the underlying call that’s made when a user calls `xbmcvs.exists`? Is it platform dependent?

**Comment by Reptarsrage** [comment]
Oh I’m sorry, after looking at the code I realized you are just a stub library. Whoops!
