### ISSUE TITLE
Raised Exceptions not shown

### ISSUE THREAD

**Issue by benjamw** [romanvm/Kodistubs#16]
I'm working on a Kodi plugin, and can't find any reference of what exceptions might be raised by the various xbmc modules.

Can this be added to kodistubs so developers will know which exceptions might need to be caught?

**Comment by romanvm** [comment]
I'm not sure what you mean. Exceptions that are documented they are... well, documented: http://romanvm.github.io/Kodistubs/_autosummary/xbmcgui.html#xbmcgui.Window

**Comment by benjamw** [comment]
My apologies. The function I was paying particular attention to must not raise any exceptions.
