### ISSUE TITLE
Update Kodistubs 19 to beta1

### ISSUE THREAD

**Issue by AnonTester** [romanvm/Kodistubs#18]
Could you please update the matrix branch to beta1?
For example, xbmc.translatePath was moved to xbmcvfs.translatePath and triggers warnings in current nightlies. This change isn't in the alpha1 stubs yet.

Thanks very much!

**Comment by romanvm** [comment]
This is in my plans, but I can't promise anything.

**Comment by oddstr13** [comment]
Do you have the process of generating the stubs documented somewhere?

**Comment by romanvm** [comment]
@oddstr13 Here's kodistubs-generator: https://github.com/romanvm/kodistubs-generator It does most of the work but generated stub files still need manual post-editing.

**Comment by romanvm** [comment]
I have finally created Kodistubs from the current Kodi source code. They can be found in `master` branch. If no major issues are found this version will be published on PyPi.
