### ISSUE TITLE
Update Kodistubs 20

### ISSUE THREAD

**Issue by rysson** [romanvm/Kodistubs#22]
Hi, thanks for this module, write addons is match easier.

I any chance (and sense) to upgrade stubs to K20?

**Comment by romanvm** [comment]
If I survive this fucking war Kodistubs will be upgraded to Kodi 20 when it's close to release and Python API is stable.

**Comment by romanvm** [comment]
Just FYI: Kodi v.20 alpha is released and I've started working on Kodistubs v.20. I cannot say when they will be released but hopefully soon.

**Comment by romanvm** [comment]
https://pypi.org/project/Kodistubs/20.0.0a1/
